In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/ratings.csv
/kaggle/input/movies.csv
/kaggle/input/toy_dataset.csv


In [2]:
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
ratings = pd.read_csv("/kaggle/input/toy_dataset.csv", index_col = 0)
ratings.fillna(0, inplace = True)

Address the missing ratings

In [4]:
def standardize(row):
    new_row = (row - row.mean())/ (row.max() - row.min())
    return new_row
ratings_std = ratings.apply(standardize)
ratings_std

action1  action2   action3  romantic1  romantic2  romantic3
user 1     0.36      0.6  0.400000      -0.65      -0.08      -0.35
user 2     0.56      0.2  0.400000      -0.15      -0.08      -0.60
user 3    -0.24     -0.4 -0.600000       0.35       0.52       0.40
user 4    -0.44      0.0 -0.266667       0.35      -0.48       0.15
user 5    -0.24     -0.4  0.066667       0.10       0.12       0.40

In [5]:
item_similarity = cosine_similarity(ratings_std.T)
print(item_similarity)

[[ 1.          0.70668875  0.81368151 -0.79941088 -0.02539184 -0.91410609]
 [ 0.70668875  1.          0.72310153 -0.84515425 -0.5189993  -0.84337386]
 [ 0.81368151  0.72310153  1.         -0.84794611 -0.3799803  -0.80218063]
 [-0.79941088 -0.84515425 -0.84794611  1.          0.14803913  0.72374686]
 [-0.02539184 -0.5189993  -0.3799803   0.14803913  1.          0.39393939]
 [-0.91410609 -0.84337386 -0.80218063  0.72374686  0.39393939  1.        ]]


In [6]:
item_similarity_df = pd.DataFrame(item_similarity, index = ratings.columns, columns = ratings.columns)
item_similarity_df

action1   action2   action3  romantic1  romantic2  romantic3
action1    1.000000  0.706689  0.813682  -0.799411  -0.025392  -0.914106
action2    0.706689  1.000000  0.723102  -0.845154  -0.518999  -0.843374
action3    0.813682  0.723102  1.000000  -0.847946  -0.379980  -0.802181
romantic1 -0.799411 -0.845154 -0.847946   1.000000   0.148039   0.723747
romantic2 -0.025392 -0.518999 -0.379980   0.148039   1.000000   0.393939
romantic3 -0.914106 -0.843374 -0.802181   0.723747   0.393939   1.000000

Let's make recommendations!

In [7]:
def get_similar_movies(movie_name, user_rating):
    similar_score = item_similarity_df[movie_name] * (user_rating - 2.5 )
    similar_score = similar_score.sort_values(ascending = False)
    return similar_score


In [8]:
print(get_similar_movies("action3", 5))

action3      2.500000
action1      2.034204
action2      1.807754
romantic2   -0.949951
romantic3   -2.005452
romantic1   -2.119865
Name: action3, dtype: float64


In [9]:
action_lover = [("action1", 5), ("romantic2", 1), ("romantic3", 1)]
similar_movies = pd.DataFrame()

In [10]:
for movie, rating in action_lover:
    similar_movies = similar_movies.append(get_similar_movies(movie, rating), ignore_index = True)

In [11]:
similar_movies.head()
similar_movies.sum().sort_values(ascending = False)

action1      3.909247
action2      3.810282
action3      3.807445
romantic2   -2.154389
romantic1   -3.306206
romantic3   -4.376174
dtype: float64

In [12]:
ratings = pd.read_csv("/kaggle/input/ratings.csv")
movies = pd.read_csv("/kaggle/input/movies.csv")
ratings = pd.merge(movies, ratings)
ratings.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating   timestamp  
0       1     4.0   964982703  
1       5     4.0   847434962  
2       7     4.5  1106635946  
3      15     2.5  1510577970  
4      17     4.5  1305696483

In [13]:
ratings.drop(['genres', 'timestamp'], axis = 1)

movieId                                      title  userId  rating
0             1                           Toy Story (1995)       1     4.0
1             1                           Toy Story (1995)       5     4.0
2             1                           Toy Story (1995)       7     4.5
3             1                           Toy Story (1995)      15     2.5
4             1                           Toy Story (1995)      17     4.5
...         ...                                        ...     ...     ...
100831   193581  Black Butler: Book of the Atlantic (2017)     184     4.0
100832   193583               No Game No Life: Zero (2017)     184     3.5
100833   193585                               Flint (2017)     184     3.5
100834   193587        Bungo Stray Dogs: Dead Apple (2018)     184     3.5
100835   193609        Andrew Dice Clay: Dice Rules (1991)     331     4.0

[100836 rows x 4 columns]

In [14]:
user_ratings = ratings.pivot_table(index = ['userId'], columns = ['title'], values = 'rating')
user_ratings.head()

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              NaN                                      NaN   
2              NaN                                      NaN   
3              NaN                                      NaN   
4              NaN                                      NaN   
5              NaN                                      NaN   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          NaN                  NaN   
2                          NaN                  NaN   
3                          NaN                  NaN   
4                          NaN                  NaN   
5                          NaN                  NaN   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             NaN                              NaN   
2                             NaN                              NaN   
3                             NaN                              NaN   
4                             NaN                              NaN   
5                             NaN                              NaN   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      NaN                   NaN                          NaN   
2                      NaN                   NaN                          NaN   
3                      NaN                   NaN                          NaN   
4                      NaN                   NaN                          NaN   
5                      NaN                   NaN                          NaN   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  NaN  ...          NaN           NaN   
2                                  NaN  ...          NaN           NaN   
3                                  NaN  ...          NaN           NaN   
4                                  NaN  ...          NaN           NaN   
5                                  NaN  ...          NaN           NaN   

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId                                           
1                 NaN                      NaN   
2                 NaN                      NaN   
3                 NaN                      NaN   
4                 NaN                      NaN   
5                 NaN                      NaN   

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId                                                           
1                                                     NaN        
2                                                     NaN        
3                                                     NaN        
4                                                     NaN        
5                                                     NaN        

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId                                                                
1                   NaN         NaN                             NaN   
2                   NaN         NaN                             NaN   
3                   NaN         NaN                             NaN   
4                   NaN         NaN                             NaN   
5                   NaN         NaN                             NaN   

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)  
userId                                                                    
1                         4.0                                        NaN  
2                         NaN                            

Drop movies with less than 10 ratings

In [15]:
user_ratings = user_ratings.dropna(thresh = 10, axis = 1).fillna(0, axis = 1)

In [16]:
print(user_ratings)

title   'burbs, The (1989)  (500) Days of Summer (2009)  \
userId                                                    
1                      0.0                          0.0   
2                      0.0                          0.0   
3                      0.0                          0.0   
4                      0.0                          0.0   
5                      0.0                          0.0   
...                    ...                          ...   
606                    0.0                          0.0   
607                    0.0                          0.0   
608                    0.0                          0.0   
609                    0.0                          0.0   
610                    0.0                          3.5   

title   10 Cloverfield Lane (2016)  10 Things I Hate About You (1999)  \
userId                                                                  
1                              0.0                                0.0   
2            

In [17]:
corrMatrix = user_ratings.corr(method='pearson')
corrMatrix.head(100)

title                              'burbs, The (1989)  \
title                                                   
'burbs, The (1989)                           1.000000   
(500) Days of Summer (2009)                  0.063117   
10 Cloverfield Lane (2016)                  -0.023768   
10 Things I Hate About You (1999)            0.143482   
10,000 BC (2008)                             0.011998   
...                                               ...   
Almost Famous (2000)                         0.099554   
Along Came Polly (2004)                      0.027287   
Along Came a Spider (2001)                   0.064762   
Amadeus (1984)                               0.136013   
Amazing Spider-Man, The (2012)               0.083419   

title                              (500) Days of Summer (2009)  \
title                                                            
'burbs, The (1989)                                    0.063117   
(500) Days of Summer (2009)                           1.000000   
10 Cloverfield Lane (2016)                            0.142471   
10 Things I Hate About You (1999)                     0.273989   
10,000 BC (2008)                                      0.193960   
...                                                        ...   
Almost Famous (2000)                                  0.209549   
Along Came Polly (2004)                               0.282426   
Along Came a Spider (2001)                           -0.003205   
Amadeus (1984)                                        0.084829   
Amazing Spider-Man, The (2012)                        0.224961   

title                              10 Cloverfield Lane (2016)  \
title                                                           
'burbs, The (1989)                                  -0.023768   
(500) Days of Summer (2009)                          0.142471   
10 Cloverfield Lane (2016)                           1.000000   
10 Things I Hate About You (1999)                   -0.005799   
10,000 BC (2008)                                     0.112396   
...                                                       ...   
Almost Famous (2000)                                 0.032088   
Along Came Polly (2004)                              0.113213   
Along Came a Spider (2001)                           0.016372   
Amadeus (1984)                                      -0.055707   
Amazing Spider-Man, The (2012)                       0.149903   

title                              10 Things I Hate About You (1999)  \
title                                                                  
'burbs, The (1989)                                          0.143482   
(500) Days of Summer (2009)                                 0.273989   
10 Cloverfield Lane (2016)                                 -0.005799   
10 Things I Hate About You (1999)                           1.000000   
10,000 BC (2008)                                            0.244670   
...                                                              ...   
Almost Famous (2000)                                        0.296727   
Along Came Polly (2004)                                     0.193085   
Along Came a Spider (2001)                                  0.085365   
Amadeus (1984)                                              0.105783   
Amazing Spider-Man, The (2012)                              0.103802   

title                              10,000 BC (2008)  101 Dalmatians (1996)  \
title                                                                        
'burbs, The (1989)                         0.011998               0.087931   
(500) Days of Summer (2009)                0.193960               0.148903   
10 Cloverfield Lane (2016)                 0.112396               0.006139   
10 Things I Hate About You (1999)          0.244670               0.223481   
10,000 BC (2008)                           1.000000               0.234459   
...                                             ...                   

Build similarity matrix

In [18]:
def get_similar(movie_name,rating):
    similar_ratings = corrMatrix[movie_name]*(rating - 2.5)
    similar_ratings = similar_ratings.sort_values(ascending = False)
    #print(type(similar_ratings))
    return similar_ratings

In [19]:
romantic_lover = [("(500) Days of Summer (2009)",5),("Alice in Wonderland (2010)",3),("Aliens (1986)",1),("2001: A Space Odyssey (1968)",2)]
similar_movies = pd.DataFrame()
for movie,rating in romantic_lover:
    similar_movies = similar_movies.append(get_similar(movie,rating),ignore_index = True)

similar_movies.head(10)

'burbs, The (1989)  (500) Days of Summer (2009)  \
0            0.157792                     2.500000   
1           -0.016276                     0.203998   
2           -0.304722                    -0.062634   
3           -0.102988                    -0.056808   

   10 Cloverfield Lane (2016)  10 Things I Hate About You (1999)  \
0                    0.356179                           0.684973   
1                    0.126834                           0.113241   
2                   -0.214700                          -0.118754   
3                   -0.049655                          -0.042987   

   10,000 BC (2008)  101 Dalmatians (1996)  \
0          0.484900               0.372257   
1          0.092218               0.085790   
2         -0.037059              -0.063992   
3         -0.021729              -0.055422   

   101 Dalmatians (One Hundred and One Dalmatians) (1961)  \
0                                           0.355353        
1                                           0.072825        
2                                          -0.170195        
3                                          -0.051115        

   12 Angry Men (1957)  12 Years a Slave (2013)  127 Hours (2010)  ...  \
0             0.399389                 0.338715          0.500338  ...   
1             0.097794                 0.083822          0.084897  ...   
2            -0.280090                -0.016283         -0.102493  ...   
3            -0.097954                -0.061595         -0.070398  ...   

   Zack and Miri Make a Porno (2008)  Zero Dark Thirty (2012)  \
0                           0.936288                 0.446637   
1                           0.159907                 0.085502   
2                          -0.147339                -0.162387   
3                          -0.075325                -0.048607   

   Zero Effect (1998)  Zodiac (2007)  Zombieland (2009)  Zoolander (2001)  \
0            0.171018       1.036463           0.889309          0.630565   
1            0.011564       0.176888           0.168302          0.121710   
2           -0.368712      -0.281119          -0.263686         -0.228562   
3           -0.128795      -0.175166          -0.098088         -0.074205   

   Zootopia (2016)  eXistenZ (1999)  xXx (2002)  ¡Three Amigos! (1986)  
0         0.540017         0.134034    0.602730               0.314763  
1         0.072590         0.025695    0.081764               0.027540  
2        -0.144292        -0.410899   -0.242935              -0.238410  
3        -0.049626        -0.153017   -0.082048              -0.091432  

[4 rows x 2269 columns]

In [20]:
action_lover = [("Amazing Spider-Man, The (2012)",5),("Mission: Impossible III (2006)",4),("Toy Story 3 (2010)",2),("2 Fast 2 Furious (Fast and the Furious 2, The) (2003)",4)]
similar_movies = pd.DataFrame()
for movie,rating in action_lover:
    similar_movies = similar_movies.append(get_similar(movie,rating), ignore_index = True)

similar_movies.head(10)
similar_movies.sum().sort_values(ascending = False).head(20)

Amazing Spider-Man, The (2012)                           3.233134
Mission: Impossible III (2006)                           2.874798
2 Fast 2 Furious (Fast and the Furious 2, The) (2003)    2.701477
Over the Hedge (2006)                                    2.229721
Crank (2006)                                             2.176259
Mission: Impossible - Ghost Protocol (2011)              2.159666
Hancock (2008)                                           2.156098
The Amazing Spider-Man 2 (2014)                          2.153677
Hellboy (2004)                                           2.137518
Snakes on a Plane (2006)                                 2.137396
Jumper (2008)                                            2.129716
Chronicles of Riddick, The (2004)                        2.121689
Tron: Legacy (2010)                                      2.111843
Fantastic Four (2005)                                    2.083022
X-Men: The Last Stand (2006)                             2.077530
Wreck-It R